package progress

import (
	"bgscan/internal/ui/shared/ui"

	"github.com/charmbracelet/bubbles/progress"
	tea "github.com/charmbracelet/bubbletea"
)

// Update handles incoming BubbleTea messages and updates the progress bar.
//
// Responsibilities:
//   - Adjust width on terminal resize
//   - Update progress percentage
//   - Process animation frames generated by the progress component
func (m *Model) Update(msg tea.Msg) (ui.Component, tea.Cmd) {

	switch msg := msg.(type) {

	// Terminal resized → recompute progress width
	case tea.WindowSizeMsg:
		m.progress.Width = m.Width()
		return m, nil

	// External progress update
	case UpdateProgressMsg:
		// When progress reaches completion, switch to a cleaner format
		if msg.Progress == 1 {
			m.progress.PercentFormat = " %3.0f%%"
		}

		return m, m.progress.SetPercent(msg.Progress)

	// progress.FrameMsg is emitted internally by the progress model
	// to animate the bar smoothly.
	case progress.FrameMsg:

		model, cmd := m.progress.Update(msg)

		if p, ok := model.(progress.Model); ok {
			m.progress = p
		}

		return m, cmd
	}

	return m, nil
}

