package engine

import (
	"bgscan/internal/core/config"
	"bgscan/internal/core/iplist"
	"bgscan/internal/logger"
	"context"
	"sync"
)

const (
	// defaultBatchSize is the default number of IPs processed in one batch for PipelineChain mode.
	defaultBatchSize = 1000
	// defaultChannelBuffer is the default buffer size for channels in ParallelChain mode.
	defaultChannelBuffer = 100
	// channelBufferMultiple defines a multiplier to set the output channel buffer size based on the next stage's worker count.
	channelBufferMultiple = 2
)

// RunScanWithChain acts as the main orchestrator for executing a scan sequence based on the configured ChainMode.
// It delegates the execution to the appropriate mode handler: SimpleChain, ParallelChain, or PipelineChain.
// It returns immediately if no stages are defined or if the context is already cancelled.
func RunScanWithChain(ctx context.Context, input string, maxIp int, cfg *ChainConfig) {
	if len(cfg.Stages) == 0 {
		return
	}

	switch cfg.Mode {
	case SimpleChain:
		executeSimpleChain(ctx, input, maxIp, cfg)
	case ParallelChain:
		executeParallelChain(ctx, input, maxIp, cfg)
	case PipelineChain:
		executePipelineChain(ctx, input, maxIp, cfg)
	}
}

// ── Simple Chain ─────────────────────────────────────────────────────────────

// executeSimpleChain runs stages sequentially. Each stage reads its input from the result file
// generated by the preceding stage. This is a disk-I/O intensive sequence.
func executeSimpleChain(ctx context.Context, input string, maxIP int, cfg *ChainConfig) {
	currentInput := input

	for i, stage := range cfg.Stages {
		if currentInput == "" {
			logger.CoreInfo("Simple Chain: Stage %d skipped (no input)", i+1)
			return
		}

		select {
		case <-ctx.Done():
			return
		default:
		}

		logger.CoreInfo("Simple Chain: Stage %d/%d starting", i+1, len(cfg.Stages))
		RunScan(ctx, currentInput, maxIP, stage, cfg.Pause)
		currentInput = stage.Writer.GetResultPath()
		logger.CoreInfo("Simple Chain: Stage %d/%d completed", i+1, len(cfg.Stages))
	}
}

// ── Parallel Chain ───────────────────────────────────────────────────────────

// executeParallelChain runs all defined stages concurrently in a true streaming pipeline fashion.
// Backpressure is managed through Go channel buffers set between stages.
// This mode offers the highest throughput but requires careful buffer tuning.
func executeParallelChain(ctx context.Context, input string, maxIp int, cfg *ChainConfig) {
	totalIPs, err := iplist.CountActiveIPs(input)
	if err != nil {
		logger.CoreError("Failed to count IPs: %v", err)
		totalIPs = 0
	}

	logger.CoreInfo("Parallel Chain: Starting %d stages concurrently, total IPs: %d", len(cfg.Stages), totalIPs)

	channels := createStageChannels(cfg)
	executors := make([]*stageExecutor, len(cfg.Stages))

	for i, stage := range cfg.Stages {
		var total uint64 = 0
		if i == 0 {
			total = totalIPs
		}
		executors[i] = newStageExecutor(ctx, stage, cfg.Pause, total)
	}

	// cleanup
	defer func() {
		for _, exec := range executors {
			exec.cleanup()
		}
	}()

	var wg sync.WaitGroup

	for i, stage := range cfg.Stages {
		wg.Add(1)

		inputCh := getInputChannel(i, channels)
		outputCh := getOutputChannel(i, len(cfg.Stages), channels)

		var next *stageExecutor
		if i+1 < len(executors) {
			next = executors[i+1]
		}

		go func(idx int, s ScanConfig, in, out chan string, exec, nextExec *stageExecutor) {
			defer wg.Done()
			defer closeOutputChannel(out)

			logger.CoreInfo("Parallel Chain: Stage %d starting", idx+1)

			if in == nil {
				streamStageFromFile(ctx, input, maxIp, s, out, exec, nextExec, cfg.Pause)
			} else {
				streamStageFromChannel(ctx, in, s, out, exec, nextExec, cfg.Pause)
			}

			logger.CoreInfo("Parallel Chain: Stage %d completed", idx+1)
		}(i, stage, inputCh, outputCh, executors[i], next)
	}

	wg.Wait()

	logger.CoreInfo("Parallel Chain: All stages completed")
}

// createStageChannels allocates the necessary buffered channels to connect N stages.
// The buffer size for a channel is calculated based on the worker count of the *next* stage.
func createStageChannels(cfg *ChainConfig) []chan string {
	channels := make([]chan string, len(cfg.Stages))

	for i := range channels {
		bufSize := defaultChannelBuffer
		if i+1 < len(cfg.Stages) {
			// Buffer size is set based on the next stage's needs to handle potential bursts.
			multiplier := max(config.GetGeneral().ChannelBufferMultiple, channelBufferMultiple)
			bufSize = cfg.Stages[i+1].Workers * multiplier
		}
		channels[i] = make(chan string, bufSize)
	}

	return channels
}

// getInputChannel returns the input channel for a given stage index. Returns nil for the first stage.
func getInputChannel(stageIdx int, channels []chan string) chan string {
	if stageIdx == 0 {
		return nil
	}
	return channels[stageIdx-1]
}

// getOutputChannel returns the output channel for a given stage index. Returns nil for the last stage.
func getOutputChannel(stageIdx, totalStages int, channels []chan string) chan string {
	if stageIdx >= totalStages-1 {
		return nil
	}
	return channels[stageIdx]
}

// closeOutputChannel safely closes a channel if it is not nil, preventing panics.
func closeOutputChannel(ch chan string) {
	if ch != nil {
		close(ch)
	}
}

// ── Pipeline Chain ───────────────────────────────────────────────────────────

// executePipelineChain implements the requested N-Stage Batch Pipeline model.
// IPs are streamed in fixed-size batches, and each batch traverses all stages sequentially
// before the next batch is started. This provides a controlled form of backpressure.

func executePipelineChain(ctx context.Context, input string, maxIp int, cfg *ChainConfig) {
	totalIPs, err := iplist.CountActiveIPs(input)
	if err != nil {
		logger.CoreError("Failed to count IPs: %v", err)
		totalIPs = 0
	}

	batchSize := calculateBatchSize(cfg)
	logger.CoreInfo("Pipeline Chain: Starting with batch size %d, total IPs: %d", batchSize, totalIPs)

	ipStream := streamIPsFromFile(ctx, input, maxIp, batchSize)

	executors := make([]*stageExecutor, len(cfg.Stages))
	for i, stage := range cfg.Stages {
		var total uint64 = 0
		if i == 0 {
			total = totalIPs
		}
		executors[i] = newStageExecutor(ctx, stage, cfg.Pause, total)
		defer executors[i].cleanup()
	}

	processBatchStream(ctx, ipStream, executors, cfg.Pause)

	for _, stage := range cfg.Stages {
		stage.Hooks.callOnScanEnd()
	}

	logger.CoreInfo("Pipeline Chain: Completed")
}

// processBatchStream processes batches through all pipeline stages sequentially.
func processBatchStream(ctx context.Context, batchStream <-chan []string, executors []*stageExecutor, pause *PauseController) {
	for batch := range batchStream {
		select {
		case <-ctx.Done():
			return
		default:
		}

		processSingleBatch(ctx, batch, executors, pause)
	}
}

// processSingleBatch processes one batch through all stages sequentially.
func processSingleBatch(ctx context.Context, batch []string, executors []*stageExecutor, pause *PauseController) {
	currentBatch := batch

	for i, exec := range executors {
		if len(currentBatch) == 0 {
			logger.CoreInfo("Pipeline: Stage %d has no IPs to process", i+1)
			return
		}

		select {
		case <-ctx.Done():
			return
		default:
		}

		if i+1 < len(executors) {
			executors[i+1].total.Add(uint64(len(currentBatch)))
		}

		logger.CoreInfo("Pipeline: Stage %d processing %d IPs", i+1, len(currentBatch))
		currentBatch = executeBatchWithExecutor(ctx, currentBatch, exec, pause)
		logger.CoreInfo("Pipeline: Stage %d completed, %d IPs passed", i+1, len(currentBatch))
	}
}

// executeBatchWithExecutor processes a batch using an existing executor.
func executeBatchWithExecutor(
	ctx context.Context,
	batch []string,
	exec *stageExecutor,
	pause *PauseController,
) []string {
	workers := getWorkerCount(exec.stage.Workers)
	inputCh := make(chan string, workers*2)

	go func() {
		defer close(inputCh)
		for _, ip := range batch {
			select {
			case inputCh <- ip:
			case <-ctx.Done():
				return
			}
		}
	}()

	var (
		mu      sync.Mutex
		results []string
	)

	runWorkerPool(ctx, workers, pause, inputCh, func(ip string) {
		if exec.processIP(ip) {
			mu.Lock()
			results = append(results, ip)
			mu.Unlock()
		}
	})

	return results
}

// calculateBatchSize determines an optimal batch size, favoring the buffer requirements
// of the second stage worker pool to prevent immediate backpressure in the batching mechanism.
func calculateBatchSize(cfg *ChainConfig) int {
	batchSize := defaultBatchSize

	if len(cfg.Stages) > 1 {
		nextWorkers := cfg.Stages[1].Workers
		minBatchSize := nextWorkers * channelBufferMultiple

		if batchSize < minBatchSize {
			batchSize = minBatchSize
		}
	}

	return batchSize
}

// streamIPsFromFile creates a read-only channel that streams IPs from the input file,
// grouping them into fixed-size batches. This abstracts file reading into a streamable format.
func streamIPsFromFile(ctx context.Context, input string, maxIp int, batchSize int) <-chan []string {
	batchCh := make(chan []string, 2) // Small buffer for batches

	go func() {
		defer close(batchCh)

		// Inner channel for raw IP streaming from the IO layer
		ipCh := make(chan string, batchSize*2)
		streamDone := make(chan error, 1)

		go func() {
			defer close(ipCh)
			// Calls the underlying IP streaming utility.
			streamDone <- iplist.StreamActiveIPs(ctx, input, maxIp, ipCh)
		}()

		batch := make([]string, 0, batchSize)
		batchNum := 0

		for ip := range ipCh {
			batch = append(batch, ip)

			if len(batch) >= batchSize {
				batchNum++
				logger.CoreInfo("Pipeline Chain: Batch #%d ready (%d IPs)", batchNum, len(batch))

				select {
				case batchCh <- batch:
					batch = make([]string, 0, batchSize) // Reset batch
				case <-ctx.Done():
					return
				}
			}
		}

		// Send any remaining IPs as the final batch.
		if len(batch) > 0 {
			batchNum++
			logger.CoreInfo("Pipeline Chain: Final batch #%d ready (%d IPs)", batchNum, len(batch))
			select {
			case batchCh <- batch:
			case <-ctx.Done():
			}
		}

		// Check for errors from the underlying stream function.
		if err := <-streamDone; err != nil && err != context.Canceled {
			logger.CoreError("StreamActiveIPs: %v", err)
		}
	}()

	return batchCh
}
